fastlane_version "1.97.2"
skip_docs

desc "Runs all the tests"
lane :test do
  scan
end

desc "Submit new beta build to Apple TestFlight"
lane :beta do
  increment_build_number
    gym(
      scheme: "EtaBoard",
      output_directory: "build"
    )
  pilot skip_waiting_for_build_processing: true
end

