fastlane_version "1.97.2"
skip_docs

xcversion version: "~> 7.3.0"

project = 'EtaBoard.xcodeproj'

desc "Runs all the tests"
lane :test do
  scan
end

desc "Submit new beta build to Apple TestFlight"
lane :beta do |options|
  ensure_git_status_clean
  increment_build_number
  gym(
    scheme: "EtaBoard",
    output_directory: "build"
  )

  if options[:submit]
    pilot skip_waiting_for_build_processing: true
  end

  commit_version_bump xcodeproj: project
  add_git_tag tag: "v#{get_version_number}.#{get_build_number}"
  push_to_git_remote
end

lane :bump_build_number_after_the_fact do
  beta(submit: false)
end

